name: Check Tasks

permissions: {}
on:
    pull_request:
        types: [opened, edited]

jobs:
  check-tasks:
    name: Check Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.11"
      - name: Check for open tasks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha}}
          GITHUB_COMMENT: ${{ github.event.comment.body }}
        run: python src/check_tasks.py
